type: object
x-stoplight:
  id: zofkvtcxt8l01
description: 'Application id and name registered within the SE Asset Management system. If the application is both an API consumer and a proxy provider, it shares one of these records.'
required:
  - assetId
  - assetName
properties:
  assetId:
    type: string
    x-stoplight:
      id: k1wbfo37ywkhz
    description: Unique asset id for this application
    example: '50600'
  assetName:
    type: string
    x-stoplight:
      id: sz3y19oox03l3
    description: Application asset name
    example: SE API Management
title: Application Asset
