type: object
x-stoplight:
  id: fe0zyow9teaq2
title: Environment Provider
description: |-
  An API provider application for a specific environment.

  A provider is also known as a backend application, a system that hosts the API service, lying behind the SEAPIM platform.
required:
  - assetId
  - createdAt
  - updatedAt
  - environment
properties:
  assetId:
    type: string
    x-stoplight:
      id: ko86y27z038z1
    example: '12345'
    description: 'Application asset id, as defined in the SE asset management system'
  providerUrls:
    type: array
    x-stoplight:
      id: qo6lrj1tqstql
    description: Provider system URL for this API
    items:
      x-stoplight:
        id: 99f18gyx7i1w0
      type: string
      format: uri
  reverseProxies:
    type: array
    x-stoplight:
      id: 4hcalbmjrrvtb
    description: 'Regional reverse proxy details, if the provided is hosted in the SE private network'
    items:
      x-stoplight:
        id: m4k2wmldrjmrg
      type: string
  instructions:
    type: string
    x-stoplight:
      id: 45w6qexixrpar
    description: Extra information to help connect with a provider
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: p8inqpzpwdvk9
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: xk59vypcxgxkq
  environment:
    $ref: ./Environment.yaml
    x-stoplight:
      id: csvxe3rrr7ogu
    description: API requirements-related SEAPIM environment
