type: object
x-stoplight:
  id: pxz2w0nsl86b9
title: Environment Provider
description: |-
  An API provider application for a specific environment.

  A provider is also known as a backend application, a system that hosts the API service, lying behind the SEAPIM platform.
required:
  - assetId
  - createdAt
  - updatedAt
  - environment
properties:
  assetId:
    type: string
    x-stoplight:
      id: r7xwh862qc1qf
    example: '12345'
    description: 'Application asset id, as defined in the SE asset management system'
  providerUrls:
    type: array
    x-stoplight:
      id: kyjmpw48yxqtm
    description: Provider system URL for this API
    items:
      x-stoplight:
        id: x6y0xwbsgb77v
      type: string
      format: uri
  reverseProxies:
    type: array
    x-stoplight:
      id: nfrk6bj4ymrmr
    description: 'Regional reverse proxy details, if the provided is hosted in the SE private network'
    items:
      x-stoplight:
        id: qltpflvhofmdn
      type: string
  instructions:
    type: string
    x-stoplight:
      id: lw84oby9zxedi
    description: Extra information to help connect with a provider
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: a7u10zfl87hsx
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: f6hjxg4r140mb
  environment:
    $ref: ./Environment.yaml
    x-stoplight:
      id: qg64d62ygfk7t
    description: API requirements-related SEAPIM environment
