type: object
x-stoplight:
  id: tt9ybhxz2f1ec
title: Environment Domain
description: This captures the list of CORS domains that need to be whitelisted for a given API proxy. Specifically thevalues that would go in the Access Control Allow Origin header.
required:
  - createdAt
  - updatedAt
properties:
  domains:
    type: array
    x-stoplight:
      id: e7vn1y51ajl32
    description: List of domains that are to be whitelisted
    items:
      x-stoplight:
        id: u6nds6xhkne4g
      type: string
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: lw37cxacc9nu5
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: 3bu5cqquazbvg
